Notebook Style Command:<br>
&emsp;**_jt -t gruvboxd -f source -nf sourcesans -nfs 8 -ofs 11 -cursc p -T -N -kl_**

In [1]:
import cv2
import math
import random
import numpy as np

from copy import copy

# Image Color Model

In [13]:
img_path = 'Pictures/myself/cwcai.jpg'
img_size = (500, 600)
img = cv2.imread(img_path)
img = cv2.resize(img, img_size)
cv2.imshow("Resize Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Grayscale

cv2 internal method

In [14]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Scale Image", img_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [ ]:
def gray_scale(src_img):
    dst_img = np.zeros((src_img.shape[0], src_img.shape[1]), dtype=np.uint8)
    for row in range(src_img.shape[0]):
        for col in range(src_img.shape[1]):
            dst_img[row, col] = .144 * src_img[row][col][0] + \
              .587 * src_img[row][col][1] + .299 * src_img[row][col][2]
    
    return dst_img

In [6]:
img_gray = gray_scale(img)
cv2.imshow("Gray Scale Image", img_gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Binary Image

cv2 internal method

In [15]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, img_binary = cv2.threshold(
    img_gray, thresh=0, maxval=255, type=cv2.THRESH_BINARY | cv2.THRESH_TRIANGLE
)
print("threshold value: {}".format(ret))
cv2.imshow("Binary Image", img_binary)

cv2.waitKey(0)
cv2.destroyAllWindows()

threshold value: 126.0


custom method

In [ ]:
def img_threshold_binary(src_img, thresh=126.0):
    dst_img = copy(src_img)
    for row in range(src_img.shape[0]):
        for col in range(src_img.shape[1]):
            dst_img[row][col] = 0 if src_img[row][col] <= thresh else 255
    
    return dst_img

In [4]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_binary = img_threshold_binary(img_gray)
cv2.imshow("Binary Image(thresh=126.0)", img_binary)

# set thresh value to mean of pixel value
h, w = img_gray.shape[:2]
m = np.reshape(img_gray, [1, h * w])
mean = m.sum()/ (h * w)
print("mean of pixel value:{}".format(mean))
img_binary = img_threshold_binary(img_gray, thresh=mean)
cv2.imshow("Binary Image(thresh={})".format(mean), img_binary)

cv2.waitKey(0)
cv2.destroyAllWindows()

mean of pixel value:144.90689333333333


# Image Noise

In [70]:
def clamp(pixel):
    if pixel > 255:
        return 255
    elif pixel < 0:
        return 0
    else:
        return pixel

## Gaussian Noise

In [3]:
img_path = 'Pictures/myself/cwcai.jpg'
img_size = (500, 500)
img = cv2.imread(img_path)
img = cv2.resize(img, img_size)
cv2.imshow("Resize Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

cv2 internal method

In [4]:
img_gaussian = cv2.GaussianBlur(img, (7, 7), 0)
cv2.imshow("Gaussian Blur Image", img_gaussian)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [68]:
def gaussian_noise(src_img, miu=0.0, sig=5.0):
    dst_img = copy(src_img)
    for row in range(dst_img.shape[0]):
        for col in range(dst_img.shape[1]):
            noise = np.random.normal(miu, sig, dst_img.shape[2])
            for i, (p, n) in enumerate(zip(dst_img[row, col], noise)):
                dst_img[row, col, i] = clamp(p + n)
    
    return dst_img

In [ ]:
img_gaussian = gaussian_noise(img)
cv2.imshow("Gaussian Noise Image(miu=0.0, sig=5.0)", img_gaussian)

img_gaussian = gaussian_noise(img, sig=25.0)
cv2.imshow("Gaussian Noise Image(miu=0.0, sig=25.0)", img_gaussian)

img_gaussian = gaussian_noise(img, miu=10.0, sig=25.0)
cv2.imshow("Gaussian Noise Image(miu=10.0, sig=25.0)", img_gaussian)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Pepper Salt Noise

custom method

In [74]:
def pepper_salt_noise(src_img, snr=.5):
    dst_img = copy(src_img)
    noise_num = int(dst_img.shape[0] * dst_img.shape[1] * (1 - snr))
    
    for i in range(noise_num):
        x = random.randint(0, dst_img.shape[0] - 1)
        y = random.randint(0, dst_img.shape[1] - 1)
        dst_img[x, y] = 255 if random.randint(0, 1) else 0
    
    return dst_img

In [75]:
img_pepper_salt = pepper_salt_noise(img)
cv2.imshow("Pepper Salt Noise Image(snr=0.5)", img_pepper_salt)

img_pepper_salt = pepper_salt_noise(img, snr=.3)
cv2.imshow("Pepper Salt Noise Image(snr=0.3)", img_pepper_salt)

img_pepper_salt = pepper_salt_noise(img, snr=.9)
cv2.imshow("Pepper Salt Noise Image(snr=0.9)", img_pepper_salt)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Filters

In [2]:
img_path = 'Pictures/myself/Amiable.jpg'
img_size = (520, 480)
img = cv2.imread(img_path)
img = cv2.resize(img, img_size)
cv2.imshow("Resize Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Mean Filter

cv2 internal method

In [5]:
img_pepper_salt = pepper_salt_nosie(img, snr=.9)
cv2.imshow("Pepper Salt Blur Image(snr=0.9)", img_pepper_salt)

img_mean_filtered = cv2.blur(img_pepper_salt, ksize=(2, 2))
cv2.imshow("cv2.blur Image", img_mean_filtered)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [10]:
def mean_filter(src_img, ksize=(3, 3)):
    h, w, c = src_img.shape
    x, y = ksize
    kernel = np.ones(ksize)
    dst_img = np.zeros((h-x+1, w-y+1, c), dtype=np.uint8)
    
    for i in range(dst_img.shape[0]):
        for j in range(dst_img.shape[1]):
            for k in range(c):
                dst_img[i, j, k] = np.sum(src_img[i:i+x, j:j+y, k] * kernel) / (x * y)
    
    return dst_img

In [11]:
img_mean_filtered = mean_filter(img_pepper_salt, ksize=(2, 2))
cv2.imshow("Mean Filtered Image", img_mean_filtered)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Median Filter

cv2 internal method

In [6]:
img_median = cv2.medianBlur(img_pepper_salt, ksize=3)
cv2.imshow("Median Filtered Image", img_median)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [12]:
def median_blur(src_img, ksize=(3, 3)):
    h, w, c = src_img.shape
    x, y = ksize
    dst_img = np.zeros((h-x+1, w-y+1, c), dtype=np.uint8)
    
    for i in range(dst_img.shape[0]):
        for j in range(dst_img.shape[1]):
            for k in range(c):
                dst_img[i, j, k] = np.median(src_img[i:i+x, j:j+y, k])
    
    return dst_img

In [14]:
img_median = median_blur(img_pepper_salt)
cv2.imshow("Median Filtered Image(ksize=(3, 3))", img_median)

img_median = median_blur(img_pepper_salt, ksize=(5, 5))
cv2.imshow("Median Filtered Image(ksize=(5, 5))", img_median)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Gaussian Filter

cv2 internal method

In [79]:
img_gaussian = cv2.GaussianBlur(img, ksize=(3, 5), sigmaX=1.0)
cv2.imshow("Gaussian Filtered Image(ksize=(3, 5), sigmaX=0.0)", img_gaussian)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [80]:
def gaussian_blur(src_img, ksize=(3, 3), sigma=1.0):
    assert ksize[0] > 0 and ksize[0] % 2 and ksize[1] > 0 and ksize[1] % 2
    
    def gaussian_kernel(kernel_size=(3, 3), sig=1.0):
        assert ksize[0] > 0 and ksize[0] % 2 and ksize[1] > 0 and ksize[1] % 2
        
        kernel = np.zeros(kernel_size, dtype=np.float32)
        x, y = kernel_size
        for i in range(kernel.shape[0]):
            for j in range(kernel.shape[1]):
                exp = (math.pow(i-int(x/2), 2) + math.pow(j-int(y/2), 2)) / 2*math.pow(sig, 2)
                kernel[i, j] = math.exp(-exp)
        
        kernel *= 1.0 / (math.sqrt(2*math.pi) * math.pow(sig, 2))
        # normalization
        kernel_sum = np.sum(kernel)
        kernel /= kernel_sum
        
        return kernel
    
    h, w, c = src_img.shape
    x, y = ksize
    dst_img = np.zeros((h-x+1, w-y+1, c), dtype=np.uint8)
    kernel = gaussian_kernel(ksize, sigma)
    print("Gaussian Kernel Matrix:\n", kernel)
    
    for i in range(dst_img.shape[0]):
        for j in range(dst_img.shape[1]):
            for k in range(c):
                dst_img[i, j, k] = np.sum(src_img[i:i+x, j:j+y, k] * kernel)
    
    return dst_img

In [81]:
cv2.imshow("Image", img)

img_gaussian_noise = gaussian_noise(img, miu=3.0, sig=5.0)
cv2.imshow("Gaussian Noise Image(miu=3.0, sig=5.0)", img_gaussian)

img_gaussian = gaussian_blur(img_gaussian_noise)
cv2.imshow("Gaussian Filtered Image(ksize=(3, 3), sigma=1.0)", img_gaussian)

cv2.waitKey(0)
cv2.destroyAllWindows()

Gaussian Kernel Matrix:
 [[0.07511361 0.12384141 0.07511361]
 [0.12384141 0.20417997 0.12384141]
 [0.07511361 0.12384141 0.07511361]]


# Image Translation

cv2 internal method

In [12]:
rows, cols = img.shape[:2]
delta_x, delta_y = (60, -50)
M = np.float32([[1, 0, delta_x], [0, 1, delta_y]])
img_trans = cv2.warpAffine(img, M, (cols, rows))
cv2.imshow("Translation Image", img_trans)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [54]:
def translation(src_img, delta_y, delta_x, dsize):
    rows, cols = dsize
    M = np.float32([[1, 0, -delta_x], [0, 1, -delta_y]])
    dst_img = np.zeros((dsize[0], dsize[1], src_img.shape[2]), dtype=np.uint8)
    
    for i in range(rows):
        for j in range(cols):
            src_pos = np.array([i, j, 1])
            x, y = np.dot(M, src_pos)
            x = int(x)
            y = int(y)
            
            if x in range(rows) and y in range(cols):
                dst_img[i][j] = src_img[x][y]
            else:
                # black color padding
                dst_img[i][j] = 0
    
    return dst_img

In [55]:
cv2.imshow("Image", img)

dsize = img.shape[:2]
img_trans = translation(img, delta_y=-100, delta_x=-50, dsize=dsize)
cv2.imshow("Translation Image", img_trans)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Rotation

cv2 internal method

In [127]:
cv2.imshow("Image", img)

h, w, c = img.shape
matrix_rotate = cv2.getRotationMatrix2D(center=(h/2, w/2), angle=45, scale=.7)
img_rotate = cv2.warpAffine(img, matrix_rotate, (h, w))
cv2.imshow("Image Rotation", img_rotate)

cv2.waitKey(0)
cv2.destroyAllWindows()

custom method

In [5]:
def rotation(src_img, angel):
    """
    angel > 0: anticlockwise; angel < 0: clockwise.
    """
    angel = -angel / 180 * math.pi
    h, w, c = src_img.shape
    dst_img = np.zeros((h, w, c), dtype=np.uint8)
    
    # x = x0 * cos(beta) + y0 * sin(beta)
    # y = x0 * -sin(beta) + yo * cos(beta)
    # where beta is the angle between (x, y) & (x0, y0)
    
    rotate_matrix = np.array([
        [math.cos(angel), math.sin(angel)],
        [-math.sin(angel), math.cos(angel)]
    ])
    
    rotate_center_first = np.array([
        [1, 0, -.5*h],
        [0, -1, .5*w]
    ])
    
    rotate_center_last = np.array([
        [1, 0, .5*h],
        [0, -1, .5*w]
    ])
    
    for i in range(h):
        for j in range(w):
            src_coordinate = np.array([i, j, 1])
            matrix_rotate_first = np.dot(rotate_center_first, src_coordinate)
            x, y = np.dot(rotate_matrix, matrix_rotate_first)
            matrix_rotate_med = np.array([x, y, 1])
            x, y = np.dot(rotate_center_last, matrix_rotate_med)
            x = int(x)
            y = int(y)
            
            if x in range(h) and y in range(w):
                dst_img[i][j] = src_img[x][y]

    return dst_img

In [218]:
img_rotate = rotation(img, angel=45)
cv2.imshow("Image Rotation 45", img_rotate)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Scaling

cv2 internal method

In [212]:
img_resize = cv2.resize(img, dsize=(img.shape[0] // 2, img.shape[1] // 2))
cv2.imshow("Image Resize", img_resize)
print("size of resize:", img_resize.shape[:2])

cv2.waitKey(0)
cv2.destroyAllWindows()

size of resize: (260, 240)


custom method

In [213]:
def resize(src_img, scale=1.0):
    """
    >1: amplification; <1: shrink.
    """
    h, w, c = src_img.shape
    dst_img = np.zeros((int(h*scale), int(w*scale), c), dtype=np.uint8)
    resize_matrix = np.array([[1/scale, 0], [0, 1/scale]])
    
    for i in range(dst_img.shape[0]):
        for j in range(dst_img.shape[1]):
            src_pos = np.array([i, j])
            x, y = np.dot(resize_matrix, src_pos)
            x = int(x)
            y = int(y)
            
            if x in range(h) and y in range(w):
                dst_img[i, j] = src_img[x, y]
    
    return dst_img

In [216]:
img_resize = resize(img, scale=.7)
cv2.imshow("Image Resize", img_resize)
print("size of resize:", img_resize.shape[:2])

cv2.waitKey(0)
cv2.destroyAllWindows()

size of resize: (336, 364)


# Image Filipping

In [2]:
img_path = 'Pictures/myself/Amiable.jpg'
img_size = (520, 480)
img = cv2.imread(img_path)
img = cv2.resize(img, img_size)
cv2.imshow("Resize Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Horizontal

In [6]:
def flip_hor(src_img):
    h, w, c = src_img.shape
    dst_img = copy(src_img)
    matrix_flip = np.array([
        [1, 0, 0],
        [0, -1, w-1]
    ])
    
    for i in range(h):
        for j in range(w):
            src_pos = np.array([i, j, 1])
            x, y = np.dot(matrix_flip, src_pos)
            dst_img[i][j] = src_img[x][y]
    
    return dst_img

In [8]:
cv2.imshow("Image", img)

img_flip_hor = flip_hor(img)
cv2.imshow("Flip Horizontal Image", img_flip_hor)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Vertical

In [3]:
def flip_ver(src_img):
    h, w, c = src_img.shape
    dst_img = copy(src_img)
    matrix_flip = np.array([
        [-1, 0, h-1],
        [0, 1, 0]
    ])
    
    for i in range(h):
        for j in range(w):
            src_pos = np.array([i, j, 1])
            x, y = np.dot(matrix_flip, src_pos)
            dst_img[i][j] = src_img[x][y]
    
    return dst_img

In [6]:
cv2.imshow("Image", img)

img_flip_ver = flip_ver(img)
cv2.imshow("Flip Vertical Image", img_flip_ver)

img_rotate = rotation(img_flip_ver, angel=180)
cv2.imshow("Image Rotation 180", img_rotate)

cv2.waitKey(0)
cv2.destroyAllWindows()